# Copyright (c) Microsoft Corporation and others. Licensed under the MIT license.
# SPDX-License-Identifier: MIT

#FROM fossology/fossology:3.4.0 as fossology
#COPY fossology_init.sh fossology_init.sh
#RUN ./fossology_init.sh

FROM node:18
ENV APPDIR=/opt/service
#RUN apk update && apk upgrade && \
#    apk add --no-cache bash git openssh

ARG BUILD_NUMBER=0
ENV CRAWLER_BUILD_NUMBER=$BUILD_NUMBER

# Ruby and Python Dependencies
#RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests curl bzip2 build-essential libssl-dev libreadline-dev zlib1g-dev cmake python3 python3-dev python3-pip xz-utils libxml2-dev libxslt1-dev libpopt0 && \
#  rm -rf /var/lib/apt/lists/* && \
#  curl -L https://github.com/rbenv/ruby-build/archive/v20180822.tar.gz | tar -zxvf - -C /tmp/ && \
#  cd /tmp/ruby-build-* && ./install.sh && cd / && \
#  ruby-build -v 2.5.1 /usr/local && rm -rfv /tmp/ruby-build-* && \
#  gem install bundler -v 2.3.26 --no-document
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
  curl \
  bzip2 \
  build-essential \
  libssl-dev \
  libreadline-dev \
  zlib1g-dev \
  cmake \
  zlib1g \
  python3 \
  python3-pip \
  python3-dev \
  xz-utils \
  libxml2-dev \
  libxslt1-dev \
  libpopt0 \
  tar \
  python3.11 \
  python3.11-venv

# Scancode
#ARG SCANCODE_VERSION="32.0.6"

WORKDIR /src/scancode

#ENV SCANCODE_HOME=/usr/local/bin

WORKDIR /src/scanning
RUN echo python3 -m venv /src/scanning

RUN python3 -m venv /src/scanning

#RUN source /src/scanning/bin/activate
ENV PATH="/src/scanning/bin:$PATH"

RUN pip install --upgrade pip setuptools wheel
RUN pip install scancode-toolkit
RUN scancode --version
